# Use postgres/example user/password credentials
services:
  backend:
    build:
      context: ./src/backend/
      dockerfile: Dockerfile
    ports:
      - 1337:8080
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_PORT: 5432

  frontend:
    build:
      context: ./src/frontend/
      dockerfile: Dockerfile
    #ports:

  db:
    build:
      context: ./src/db/
      dockerfile: Dockerfile
    #image: postgres
    #restart: always
    # set shared memory limit when using docker compose
    #shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - kpo-postgresql-data:/var/lib/postresql
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  kpo-postgresql-data:
